---
label: Project
hide_body: false
fields:
- type: text
  name: DekkoSECURE_Home
  label: DekkoSECURE Home
  description: Demand DekkoSECURE for confidential communication and collaboration.
    The only platform built with security first
- type: text
  name: DekkoSECURE
  label: DekkoSECURE
  description: Demand DekkoSECURE for confidential communication and collaboration.
    The only platform built with security first
- type: file
  name: image
  label: image
- type: file
  name: bg_image
  label: bg image
  description: page header background image
- type: text
  name: category
  label: category
  description: Filter Category
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: label
    label: label
  - type: text
    name: info
    label: info
